### ISSUE TITLE
/run/tinyproxy missing

### ISSUE THREAD

**Issue by baliqci** [juju4/ansible-tinyproxy#2]
Centos 9

```yaml
- name: Create pid directory
  file:
    path: /run/tinyproxy
    state: directory
    owner: tinyproxy
    group: tinyproxy
    mode: 0775
```
